Adds severity level
autotraderuk/oliver-twist pull request #23
Opened 2021-01-13 22:00 UTC by dorzey

Warnings will not cause a "🔀 Twisted!" response.

The config now looks like this:
```
universal:
    - id: no-rejoin-models
      enabled: true
      severity: error
```

and the report like this:
<img width="1411" alt="tmp" src="https://user-images.githubusercontent.com/61307/104515172-56afc480-55ea-11eb-92a4-b0b38e3a2829.png">

2021-01-14 10:00 UTC, bloomonkey requested changes
Looking good.
A few suggestions below for slightly more pythonic code

2021-01-14 20:47 UTC, dorzey commented on olivertwist/reporter/model.py
> +        warned: int,
I think we need to look at refactoring this whole class in a separate issue. It seems like there is a lot of code!

2021-01-15 09:31 UTC, bloomonkey requested changes
One potential bug, that might not be an issue now, but might bite us in future...

2021-01-15 09:31 UTC, bloomonkey commented on olivertwist/main.py
> +    if result.has_warnings:
I didn't spot this before, but this order means that any warning will downgrade the colour from `red` to `yellow`. Probably not an issue while rule severity is set universally but could bite us in future. How about:

```python
def get_colour(result: Result):
    if result.has_errors:
        return "red"
    elif result.has_warnings:
        return "yellow"
    return "green"
```

2021-01-15 14:07 UTC, merged